title: Sergey G.  # Title

logo: avatar.jpeg

description: Between Blue and Red

show_downloads: false

theme: jekyll-theme-minimal 

# plugins:
#   - jekyll-seo-tag 

# google_site_verification: "" 

email: fs.leito@gmail.com # Allow visitors to contact you
